kind: pipeline
name: default

steps:
- name: build_dev
  image: plugins/docker
  settings:
    tag: dev-env
    target: dev
    repo: docker.netsoc.co/public/windlass
    registry: docker.netsoc.co
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - push
    branch:
      - master
- name: build_prod
  image: plugins/docker
  settings:
    tag: latest
    repo: docker.netsoc.co/netsoc/windlass
    registry: docker.netsoc.co
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - push
    branch:
      - master

- name: discord_notif
  image: appleboy/drone-discord
  environment:
    WEBHOOK_ID:
      from_secret: discord_webhook_id
    WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  settings:
    username: Netsoc CI
    avatar_url: https://raw.githubusercontent.com/drone/brand/3051b0d85318a2a20b62927ba19fc07e24c0d751/logos/png/white/drone-logo-png-white-256.png
    color: "#42f483"
    message: Windlass successfully built and pushed. Build num {{build.number}}. [Link]({{build.link}})
  when:
    event: 
      - push
    branch: 
      - master 
    status:
      - success

- name: discord_notif
  image: appleboy/drone-discord
  environment:
    WEBHOOK_ID:
      from_secret: discord_webhook_id
    WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  settings:
    username: Netsoc CI
    avatar_url: https://raw.githubusercontent.com/drone/brand/3051b0d85318a2a20b62927ba19fc07e24c0d751/logos/png/white/drone-logo-png-white-256.png
    color: "#e04414"
    message: Windlass failed for {{build.author}}. Build num {{build.number}}. [Link]({{build.link}})
  when:
    event: 
      - push
    branch: 
      - master 
    status:
      - failure           